### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by dominikg** [svitejs/vitest-plugin-playwright-e2e#1]
### Describe the problem

no docs

### Describe the proposed solution

write them

### Alternatives considered

none

### Importance

i cannot use vitest-plugin-playwright-e2e without it

**Comment by moodiest** [comment]
Hey there @dominikg , I just wanted to ask whether this plugin is still being worked on?

**Comment by dominikg** [comment]
I'm quite busy these days. 

for e2e i recommend you take a look at using `@playwright/test` directly to be able to use their advanced features like https://playwright.dev/docs/trace-viewer 

for component testing there are efforts from both vitest and playwright that may improve the situation so that you're able to use a real browser env instead of jsdom or happy-dom.

Once the situation has cleared up where vitest and playwright are heading and how this plugin might fit in it'll be picked up.

**Comment by moodiest** [comment]
> I'm quite busy these days.
> 
> for e2e i recommend you take a look at using `@playwright/test` directly to be able to use their advanced features like https://playwright.dev/docs/trace-viewer
> 
> for component testing there are efforts from both vitest and playwright that may improve the situation so that you're able to use a real browser env instead of jsdom or happy-dom.
> 
> Once the situation has cleared up where vitest and playwright are heading and how this plugin might fit in it'll be picked up.

Thanks for the update, appreciate it!
